# Custom Metabase image with DuckDB driver
# Uses Debian base to avoid glibc issues with the DuckDB plugin

FROM eclipse-temurin:21-jre-jammy

ENV MB_PLUGINS_DIR=/home/plugins/

# Download Metabase jar
ADD https://downloads.metabase.com/v0.52.9/metabase.jar /home/metabase.jar

# Download DuckDB driver
ADD https://github.com/motherduckdb/metabase_duckdb_driver/releases/download/1.5.1.0/duckdb.metabase-driver.jar /home/plugins/duckdb.metabase-driver.jar

RUN chmod 744 /home/plugins/duckdb.metabase-driver.jar

EXPOSE 3000

CMD ["java", "-jar", "/home/metabase.jar"]